services:
  # MQTT Broker - Message Hub
  mosquitto:
    image: eclipse-mosquitto:2.0-openssl
    container_name: gestione-impianto-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./data/mosquitto:/mosquitto/data
      - ./logs/mosquitto:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - impianto-network

  # InfluxDB - Time Series Database (WITH CORS)
  influxdb:
    image: influxdb:2.7-alpine
    container_name: gestione-impianto-db
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=factory
      - DOCKER_INFLUXDB_INIT_BUCKET=industrial_data
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=factory-token-2024
      - INFLUXD_REPORTING_DISABLED=true
      - INFLUXD_HTTP_CORS_ENABLED=true
      - INFLUXD_HTTP_CORS_ORIGIN="*"
    volumes:
      - impianto_influxdb_data:/var/lib/influxdb2
      - impianto_influxdb_config:/etc/influxdb2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - impianto-network

  # Event Processor - Python Service
  event-processor:
    build:
      context: ./mqtt-processor
      dockerfile: Dockerfile
    container_name: gestione-impianto-processor
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=factory-token-2024
      - INFLUXDB_ORG=factory
      - INFLUXDB_BUCKET=industrial_data
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PROCESSING_BATCH_SIZE=100
      - ANOMALY_DETECTION_ENABLED=true
      - TEMP_WARNING_THRESHOLD=80.0
      - TEMP_CRITICAL_THRESHOLD=90.0
      - VIBRATION_WARNING_THRESHOLD=2.5
    depends_on:
      mosquitto:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs/processor:/app/logs
    networks:
      - impianto-network

  # ML API Backend
  ml-api:
    build:
      context: ./dashboard/api
      dockerfile: Dockerfile
    container_name: gestione-impianto-ml-api
    ports:
      - "5001:5000"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=factory-token-2024
      - INFLUXDB_ORG=factory
      - INFLUXDB_BUCKET=industrial_data
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      influxdb:
        condition: service_healthy
      event-processor:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./mqtt-processor/src:/app/mqtt_src:ro
      - ./logs/ml-api:/app/logs
    networks:
      - impianto-network

  # Nginx for Dashboard
  dashboard:
    image: nginx:alpine
    container_name: gestione-impianto-dashboard
    ports:
      - "3000:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - influxdb
      - ml-api
    restart: unless-stopped
    networks:
      - impianto-network

  # Simulator Service
  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: gestione-impianto-simulator
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - TIME_MULTIPLIER=10
      - PIECE_COUNT=5
      - PYTHONUNBUFFERED=1
    depends_on:
      mosquitto:
        condition: service_healthy
      event-processor:
        condition: service_started
    restart: "no"
    volumes:
      - ./logs/simulator:/app/logs
    networks:
      - impianto-network

# Persistent Volumes
volumes:
  impianto_influxdb_data:
    driver: local
    name: gestione_impianto_influxdb_data
  impianto_influxdb_config:
    driver: local
    name: gestione_impianto_influxdb_config

# Network Configuration
networks:
  impianto-network:
    driver: bridge
    name: gestione-impianto-network
    ipam:
      config:
        - subnet: 172.25.0.0/16