services:
  # MQTT Broker - Message Hub
  mosquitto:
    image: eclipse-mosquitto:2.0-openssl
    container_name: gestione-impianto-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./data/mosquitto:/mosquitto/data
      - ./logs/mosquitto:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - impianto-network

  # InfluxDB - Time Series Database
  influxdb:
    image: influxdb:2.7-alpine
    container_name: gestione-impianto-db
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=factory
      - DOCKER_INFLUXDB_INIT_BUCKET=industrial_data
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=factory-token-2024
      - INFLUXD_REPORTING_DISABLED=true
    volumes:
      - impianto_influxdb_data:/var/lib/influxdb2
      - impianto_influxdb_config:/etc/influxdb2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - impianto-network

  # Grafana - Dashboard & Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: gestione-impianto-dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - impianto_grafana_data:/var/lib/grafana
      # Corrected paths to match your structure
      - ./dashboard/provisioning:/etc/grafana/provisioning:ro
      - ./dashboard/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - impianto-network

  # Event Processor - Python Service
  event-processor:
    build:
      context: ./mqtt-processor  # Corrected path
      dockerfile: Dockerfile
    container_name: gestione-impianto-processor
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=factory-token-2024
      - INFLUXDB_ORG=factory
      - INFLUXDB_BUCKET=industrial_data
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PROCESSING_BATCH_SIZE=100
      - ANOMALY_DETECTION_ENABLED=true
      - TEMP_WARNING_THRESHOLD=80.0
      - TEMP_CRITICAL_THRESHOLD=90.0
      - VIBRATION_WARNING_THRESHOLD=2.5
    depends_on:
      mosquitto:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs/processor:/app/logs
    networks:
      - impianto-network

# Persistent Volumes
volumes:
  impianto_influxdb_data:
    driver: local
    name: gestione_impianto_influxdb_data
  impianto_influxdb_config:
    driver: local
    name: gestione_impianto_influxdb_config
  impianto_grafana_data:
    driver: local
    name: gestione_impianto_grafana_data

# Network Configuration
networks:
  impianto-network:
    driver: bridge
    name: gestione-impianto-network
    ipam:
      config:
        - subnet: 172.25.0.0/16